fos_rest:
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
  format_listener:
    rules:
      - { path: '^/api/', priorities: [ 'json' ], fallback_format: 'json' }
  exception:
    enabled: true
