fos_rest:
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
    mime_types:
      json: [ 'application/json;version=1.0', 'application/json;version=2.0' ]
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
  format_listener:
    rules:
      - { path: '^/api/', priorities: [ 'json' ], fallback_format: 'json' }
  exception:
    enabled: true
  versioning:
    enabled: true
    resolvers:
      media_type: # Accept header
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'
